def linha():
    print('-='*15)

futebol = ('Botafogo', 'Flamengo', 'Bahia', 'Athletico-PR', 'Palmeiras', 'São Paulo', 'Bragantino', 'Cruzeiro', 'Atlético-MG', 'Internacional', 'Juventude', 'Fortaleza', 'Atlético-GO', 'Cuiabá', 'Vasco', 'Corinthians', 'Grêmio', 'Criciúma', 'Fluminense', 'Vitória')
linha()
print(f'Lista de Times do Brasileirão: {futebol}')
linha()
print(f'Os 5 primeiros são: {futebol[0:5]}')
linha()
print(f'Os 4 últimos são: {futebol[-4:]}')
linha()
print(f'Times em ordem alfabética: {sorted(futebol)}')
linha()
print(f'O São Paulo está na {futebol.index("São Paulo")+1}ª')
linha() 
print('O Chapecoense não esta na tabela de 2024.')